### ISSUE TITLE
VCS recommendations

### ISSUE THREAD

**Issue by JarLowrey** [HiFaraz/node-playbook#8]
Add GitLab as VCS. Link all 3 to the sites. GitLab is cheapest w/ a lot of cool features (KanBan boards). GitHub is most well known, BitBucket has Atlassian integration, and is also cheaper than GitHub.
https://github.com/pricing
https://about.gitlab.com/pricing/
https://bitbucket.org/product/pricing

Is source tree really necessary? IDK as I've never used it before. But the source says only for Windows & Mac. I'd think you'd want to encourage devs to use a Linux OS, and learn Git.

**Comment by HiFaraz** [comment]
Thanks for contributing! 

As we discussed in the Reddit thread, I'm limiting the playbook to just one recommendation in order to reduce decision making in getting started.

SourceTree: added it because it is a good solution that gets you started _fast_. Switching to Linux may be the _best_ solution overall but it is overkill for the specific problem of "Git GUI" for those that want one. There is a switching cost.

That being said, I'd welcome a PR adding OS-specific options.

**Comment by JarLowrey** [comment]
Ok good points. I recommended mentioning GitLab as you currently mention both GitHub and BitBucket

> Create a new repo on either GitHub or BitBucket 
> 
> Repository (repo) hosting: GitHub
>     for private repos: either pay GitHub or use BitBucket instead

Personally I think GitLab > BitBucket (for private repos), but it doesn't matter too much either way.

**Comment by HiFaraz** [comment]
Fair enough. I'm eliminating the confusion by only recommending GitHub. See #11

**Comment by krokofant** [comment]
I think it would be beneficial to note that students get unlimited free private repos

**Comment by HiFaraz** [comment]
Done. Thank you!
